Module8 task1 #final #4
htmlacademy-javascript/2256781-kekstagram-29 pull request #8
Opened 2023-07-05 23:02 UTC by Dimaggio-IT

2023-07-06 15:21 UTC, craz3r requested changes

2023-07-06 15:21 UTC, craz3r commented on js/util.js
> +const showAlert = (domContainer = null, message = 'error', cb = () => void 0) => {
Лучше не использовать такие конструкции как void 0
Это не используется в современной разработке и лишь сбивает с толку, если нужно запрограммировать пустую функцию лучше воспользоваться формой `() => {}`

2023-07-06 15:21 UTC, craz3r commented on js/util.js
> +function AlertMessageOptions() {
Проще сделать это обычным объектом без функции конструктора. В данном случае никакой необходимости в конструкторе нет, объект хранит статичные данные и не содержит методов

2023-07-06 15:21 UTC, craz3r commented on js/full-size.js
> +  const objClicked = filterObject(data, 'id', +idClicked)[0];
Проще воспользоваться методом find

2023-07-06 15:21 UTC, craz3r commented on js/full-size.js
> +  const previewBoxHideElements = [previewBoxElement.children[0], previewBoxElement.children[1]];
Можно было завести отдельные переменные поместив туда previewBoxElement.children[0] и previewBoxElement.children[1], сейчас непонятно о каких элементах идет речь

2023-07-07 07:15 UTC, Dimaggio-IT commented on js/util.js
> +const showAlert = (domContainer = null, message = 'error', cb = () => void 0) => {
ок

2023-07-07 07:20 UTC, Dimaggio-IT commented on js/util.js
> +function AlertMessageOptions() {
ок

2023-07-07 07:36 UTC, Dimaggio-IT commented on js/full-size.js
> +  const objClicked = filterObject(data, 'id', +idClicked)[0];
ок

2023-07-07 07:45 UTC, Dimaggio-IT commented on js/full-size.js
> +  const previewBoxHideElements = [previewBoxElement.children[0], previewBoxElement.children[1]];
ок

2023-07-07 08:36 UTC, merged